#Definir nombre del microservicio.
spring:
  application:
    name: msvc-student
  #Configuracion temporal para lenvantar los microservicios sin problema.
  config:
    import: optional:configserver:http://localhost:8888