#Definir puerto para el microservicio.
server:
  port: 8090

#Definir nombre del microservicio.
spring:
  application:
    name: msvc-student

  #Configurar la base de datos.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsDB
    username: root
    password: maen
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  #Configuracion temporal para lenvantar los microservicios sin problema.
  config:
    import: optional:configserver:http://localhost:8888

#Configuracion para registrar este microservicio en eureka.
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka