#Definir nombre al microservicio.
spring:
  application:
    name: msvc-eureka

  #Configuracion tempporal para lenvantar los microservicios sin problema.
  config:
    import: optional:configserver:http://localhost:8888