#Configuracion para redirigir a los microservicos.
spring:
  application:
    name: msvc-gateway
  #Configuracion temporal para lenvantar los microservicios sin problema.
  config:
    import: optional:configserver:http://localhost:8888